name: Compile Test

on: 
  pull_request:
    branches:
      - master
    
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      
    steps:
      - name: Checkout JSLBotBridge
        uses: actions/checkout@v2
        with:
          path: JSLBotBridge
      - name: Checkout JavaCore
        uses: actions/checkout@v2
        with:
          repository: 'CoagulateSL/JavaCore'
          path: JavaCore
      - name: Checkout SLCore
        uses: actions/checkout@v2
        with:
          repository: 'CoagulateSL/SLCore'
          path: SLCore        
      - name: Checkout JSLBot
        uses: actions/checkout@v2
        with:
          repository: 'CoagulateSL/JSLBot'
          path: JSLBot
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven
        env: 
          PACKAGE_READ: ${{ secrets.PACKAGE_READ }}
        working-directory: JSLBotBridge
        run: mvn --batch-mode --update-snapshots verify -s $GITHUB_WORKSPACE/JSLBotBridge/settings.xml
